name: Lint Shell Scripts

description: A composite action for linting shell scripts.

inputs:
  shellcheck-version:
    description: The version of shellcheck to use.
    default: 0.11.0
    required: false

runs:
  using: composite
  steps:
    - name: Setup shellcheck
      run: ${{ github.action_path }}/src/setup_shellcheck.sh
      shell: sh
      env:
        SHELLCHECK_VERSION: ${{ inputs.shellcheck-version }}

    - name: Lint Shell Scripts
      run: |-
        find . \( -path '*/.git' -o -path '*/.local' \) -prune -o -name '*.sh' -exec shellcheck {} +
      shell: sh
